"""initial schema: users, maintenance_requests, escalation_logs

Revision ID: 38d634b582a0
Revises: 
Create Date: 2026-08-19 12:54:00.143984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d634b582a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'admin', name='roleenum'), server_default=sa.text("'employee'"), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('IT', 'Facilities', 'Infrastructure', 'Other', name='categoryenum'), server_default=sa.text("'Other'"), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', name='priorityenum'), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'In Progress', 'Resolved', 'Escalated', name='statusenum'), server_default=sa.text("'Pending'"), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_created_at', 'maintenance_requests', ['created_at'], unique=False)
    op.create_index('ix_requests_status', 'maintenance_requests', ['status'], unique=False)
    op.create_table('escalation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('escalated_from', sa.String(length=100), nullable=True),
    sa.Column('escalated_to', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_logs_request_id'), 'escalation_logs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE: hand-adjusted from the autogenerated version. Autogenerate
    # ordered this as "drop index, then drop table" for every table,
    # but MySQL refuses to drop an index that's still backing a FK
    # constraint (error 1553). op.drop_table() removes a table's
    # indexes and constraints together, so for FK-backed indexes we
    # just drop the table directly, in child-to-parent order.
    op.drop_table('escalation_logs')
    op.drop_index('ix_requests_status', table_name='maintenance_requests')
    op.drop_index('ix_requests_created_at', table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
