from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    DateTime,
    ForeignKey,
    Index,
    text,
)
from sqlalchemy.schema import FetchedValue
from sqlalchemy.orm import relationship

from app.database import Base
from app.enums import RoleEnum, CategoryEnum, PriorityEnum, StatusEnum, smart_enum_column

__all__ = [
    "RoleEnum",
    "CategoryEnum",
    "PriorityEnum",
    "StatusEnum",
    "User",
    "MaintenanceRequest",
    "EscalationLog",
]

# Every timestamp in this schema is generated by MySQL itself
# (CURRENT_TIMESTAMP / ON UPDATE CURRENT_TIMESTAMP via server_default),
# never by Python's datetime.utcnow(). That keeps the value correct
# regardless of whether a row is written through the ORM, a migration,
# or raw SQL, and avoids app-server/DB clock drift. `resolved_at` is the
# one deliberate exception: it's only set on a specific status
# transition, so it's assigned explicitly in application code.


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    name = Column(String(120), nullable=False)
    email = Column(String(150), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    role = Column(
        smart_enum_column(RoleEnum),
        nullable=False,
        server_default=text(f"'{RoleEnum.employee.value}'"),
    )
    department = Column(String(100), nullable=True)
    created_at = Column(DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP"))

    # Two distinct relationships to MaintenanceRequest, disambiguated by
    # foreign_keys= on each side: a user can *own* requests (employee_id)
    # and separately be *assigned to* requests (assigned_to). Collapsing
    # these into one relationship would make SQLAlchemy unable to tell
    # which FK a given row should join on.
    requests = relationship(
        "MaintenanceRequest",
        back_populates="employee",
        foreign_keys="MaintenanceRequest.employee_id",
    )
    assigned_requests = relationship(
        "MaintenanceRequest",
        back_populates="assignee",
        foreign_keys="MaintenanceRequest.assigned_to",
    )


class MaintenanceRequest(Base):
    __tablename__ = "maintenance_requests"

    id = Column(Integer, primary_key=True)
    # RESTRICT (not CASCADE): deleting a user must not silently wipe the
    # maintenance history they created. If a user needs to be removed,
    # their requests have to be reassigned/archived first -- a deliberate
    # decision, not an oversight (see final report).
    employee_id = Column(
        Integer, ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )
    title = Column(String(150), nullable=False)
    description = Column(Text, nullable=False)
    category = Column(
        smart_enum_column(CategoryEnum),
        nullable=False,
        server_default=text(f"'{CategoryEnum.Other.value}'"),
    )
    priority = Column(
        smart_enum_column(PriorityEnum),
        nullable=False,
        server_default=text(f"'{PriorityEnum.Medium.value}'"),
    )
    status = Column(
        smart_enum_column(StatusEnum),
        nullable=False,
        server_default=text(f"'{StatusEnum.Pending.value}'"),
    )
    # SET NULL (not RESTRICT/CASCADE): unassigning/removing an assignee
    # must never delete or block deletion of the request itself -- the
    # ticket just becomes unassigned again.
    assigned_to = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    escalation_level = Column(Integer, nullable=False, server_default=text("0"))
    created_at = Column(DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP"))
    updated_at = Column(
        DateTime,
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        server_onupdate=FetchedValue(),
    )
    resolved_at = Column(DateTime, nullable=True)

    employee = relationship("User", back_populates="requests", foreign_keys=[employee_id])
    assignee = relationship(
        "User", back_populates="assigned_requests", foreign_keys=[assigned_to]
    )
    # CASCADE at the DB level (ondelete on the FK below) + delete-orphan
    # at the ORM level: escalation history belongs entirely to its
    # request and must never outlive it or exist without it.
    logs = relationship(
        "EscalationLog",
        back_populates="request",
        cascade="all, delete-orphan",
        order_by="EscalationLog.escalated_at",
    )

    __table_args__ = (
        # Supports GET /requests (admin, optional ?status_filter=) and
        # any dashboard "count by status" query.
        Index("ix_requests_status", "status"),
        # Supports the .order_by(created_at.desc()) already used by
        # GET /requests and GET /requests/my.
        Index("ix_requests_created_at", "created_at"),
        # employee_id and assigned_to are not separately indexed here:
        # MySQL/InnoDB auto-creates an index on a FK column to support
        # the constraint, so GET /requests/my (filter by employee_id)
        # and assignment lookups (filter by assigned_to) are already
        # covered without a redundant explicit index.
    )


class EscalationLog(Base):
    __tablename__ = "escalation_logs"

    id = Column(Integer, primary_key=True)
    request_id = Column(
        Integer,
        ForeignKey("maintenance_requests.id", ondelete="CASCADE"),
        nullable=False,
        # Supports "get escalation history for this request" -- the
        # only query pattern this table serves. Also auto-created by
        # the FK constraint itself, listed here for clarity.
        index=True,
    )
    escalated_from = Column(String(100), nullable=True)
    escalated_to = Column(String(100), nullable=True)
    reason = Column(String(255), nullable=False)
    escalated_at = Column(DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP"))

    request = relationship("MaintenanceRequest", back_populates="logs")
